apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    name: redis
spec:
  containers:
  - image: redis
    name: redis
    args: ["/home/redis.conf"]
    volumeMounts:
    - mountPath: /home
      name: config
  volumes:
  - name: config
    configMap:
      name: smsg-config
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  selector:
    name: redis
