apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: smsgproc-deployment
spec:
  replicas: 1
  template: 
    metadata:
      labels:
        app: smsgproc
    spec:
      containers:
      - name: smsgproc
        image: smsgproc:0.1.0
        args: ["/home/configs/smsgproc.yaml"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - mountPath: /home/configs
          name: configs
      volumes:
      - name: configs
        configMap:
          name: smsg-config
---
apiVersion: v1
kind: Service
metadata:
  name: smsgproc-monitor
spec:
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
  selector:
    app: smsgproc
