# Generated by Django 4.1.1 on 2022-10-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0002_job_created_at_job_updated_at_alter_job_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('middlename', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=255)),
                ('salary_expectation', models.DecimalField(decimal_places=2, max_digits=32)),
                ('timezone', models.CharField(max_length=16)),
                ('resume', models.BinaryField()),
                ('cover_letter', models.BinaryField()),
                ('jobs', models.ManyToManyField(to='jobs.job')),
            ],
        ),
    ]
