# Generated by Django 4.1.1 on 2022-10-08 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_alter_candidate_address_alter_candidate_cover_letter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='middlename',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='name',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='surname',
        ),
        migrations.AlterField(
            model_name='candidatejobstep',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='candidates.candidate'),
        ),
    ]
