# Generated by Django 4.1.1 on 2022-10-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_tags'),
        ('candidates', '0003_rename_middlename_candidate_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='jobs',
            field=models.ManyToManyField(blank=True, to='jobs.job'),
        ),
    ]
