# Generated by Django 4.1.1 on 2022-10-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_created_at_job_updated_at_alter_job_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='tags',
            field=models.ManyToManyField(blank=True, to='jobs.tag'),
        ),
    ]
