# Generated by Django 4.1.1 on 2022-10-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='category',
        ),
        migrations.RemoveField(
            model_name='job',
            name='city',
        ),
        migrations.RemoveField(
            model_name='job',
            name='country',
        ),
        migrations.RemoveField(
            model_name='job',
            name='education',
        ),
        migrations.RemoveField(
            model_name='job',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='job',
            name='max_hours',
        ),
        migrations.RemoveField(
            model_name='job',
            name='max_salary',
        ),
        migrations.RemoveField(
            model_name='job',
            name='min_hours',
        ),
        migrations.RemoveField(
            model_name='job',
            name='min_salary',
        ),
        migrations.RemoveField(
            model_name='job',
            name='remote',
        ),
        migrations.RemoveField(
            model_name='job',
            name='street',
        ),
        migrations.RemoveField(
            model_name='job',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='job',
            name='address',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, choices=[('R', 'Remote'), ('H', 'Hybrid'), ('O', 'On-site')], max_length=1, null=True),
        ),
    ]
