# Generated by Django 4.1.1 on 2022-10-09 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_job_employment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='photo',
        ),
    ]
